akun/urls.py
from django.urls import path
from . import views

app_name ='akun'

urlpatterns = [
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.profile_dua , name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.update_profile , name = 'update_profile')
]

assessment/urls.py
from django.urls import path

from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),
    path('delete/', views.retake, name='retake')
]

coronahworry/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workout/', include(('workout.urls', 'workout'), namespace = 'workout')),
    path('profile/', include(('akun.urls', 'akun'), namespace = 'akun')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('curhat/', include(('komentar.urls', 'komentar'), namespace = 'komentar')),
    path('curhat/', include(('postingan.urls', 'postingan'), namespace = 'postingan')),
    path('', include(('main.urls', 'main'), namespace='main')),
]



assessment/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Assessment(models.Model):
    yes = True
    no = False
    BOOLEAN_CHOICES = [(yes, 'Ya'), (no, 'Tidak/Tidak Tahu')]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    suhu = models.BooleanField(choices=BOOLEAN_CHOICES)
    sesak = models.BooleanField(choices=BOOLEAN_CHOICES)
    batuk = models.BooleanField(choices=BOOLEAN_CHOICES)
    kontak_positif = models.BooleanField(choices=BOOLEAN_CHOICES)
    kontak_gejala = models.BooleanField(choices=BOOLEAN_CHOICES)

assessment/forms.py
from django import forms
from assessment.models import Assessment


class AssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment
        fields = {
            'suhu',
            'batuk',
            'kontak_positif',
            'kontak_gejala',
            'sesak'
        }

assessment/views.py
from django.shortcuts import render, redirect
from assessment.models import Assessment
from assessment.forms import AssessmentForm

# Create your views here.


def index(request):
    if request.user.is_authenticated:
        data = Assessment.objects.filter(user=request.user)
        if(len(data) == 0):
            form = AssessmentForm(request.POST or None)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.save()
                return redirect('assessment:result')

            context = {
                'form': form
            }
            return render(request, 'assessment/assessment.html', context)
        else:
            if(data[0].user == request.user):
                return redirect('assessment:result')
    else:
        return redirect('main:login')


def retake(request):
    if request.user.is_authenticated:
        data = Assessment.objects.get(user=request.user)
        if request.method == "POST":
            data.delete()
            return redirect('assessment:index')


def result(request):
    data = Assessment.objects.filter(user=request.user)
    if(len(data) != 0):
        counterGejala = 0
        if(data[0].suhu == True):
            counterGejala += 1
        if(data[0].sesak == True):
            counterGejala += 1
        if(data[0].batuk == True):
            counterGejala += 1

        if(counterGejala == 0):
            if(data[0].kontak_gejala == True and data[0].kontak_positif == True):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == True and data[0].kontak_positif == False):
                return render(request, 'assessment/low.html')
            elif(data[0].kontak_gejala == False and data[0].kontak_positif == True):
                return render(request, 'assessment/low.html')
            else:
                return render(request, 'assessment/low.html')

        elif(counterGejala == 1):
            if(data[0].kontak_gejala == True and data[0].kontak_positif == True):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == True and data[0].kontak_positif == False):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == False and data[0].kontak_positif == True):
                return render(request, 'assessment/medium.html')
            else:
                return render(request, 'assessment/low.html')

        else:
            if(data[0].kontak_gejala == True and data[0].kontak_positif == True):
                return render(request, 'assessment/high.html')
            elif(data[0].kontak_gejala == True and data[0].kontak_positif == False):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == False and data[0].kontak_positif == True):
                return render(request, 'assessment/high.html')
            else:
                return render(request, 'assessment/medium.html')
    else:
        return render('assessment:index')

templates/assessment/assessment.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {% block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/assessment.css' %}" />
{% endblock %} {%block content%}
<div>
  <div class="assessTitleDiv">
    <h1 class="assessTitle">
      Corona Assesment
      <img
        src="https://vik.kompas.com/viruscorona/images/virus.png"
        alt="virus"
      />
    </h1>
    {{data}}
  </div>
  <form method="POST">
    {% csrf_token %}
    <div>
      <div class="questionDiv">
        <label
          >Apakah anda mengalami demam dengan suhu di atas 38°C
          (100.4°F)?</label
        >
        {{form.suhu}}
      </div>
      <div class="questionDiv">
        <label>Apakah ada batuk (atau disertai dengan batuk)?</label>
        {{form.batuk}}
      </div>
      <div class="questionDiv">
        <label
          >Apakah anda mengalami sesak saat bernafas (tekanan pada dada)?</label
        >
        {{form.sesak}}
      </div>
      <div class="questionDiv">
        <label
          >Apakah terdapat riwayat kontak (misalnya: berjabat tangan, mengobrol
          lama, berada dalam satu ruangan) dengan orang yang sudah dinyatakan
          positif terinfeksi virus Corona dalam 14 hari terakhir?</label
        >
        {{form.kontak_positif}}
      </div>
      <div class="questionDiv">
        <label
          >Apakah ada kontak (misalnya: berjabat tangan, mengobrol lama, berada
          dalam satu ruangan) dengan orang yang memiliki gejala flu, yaitu
          demam, batuk, dan pilek, atau dengan orang yang diduga terinfeksi
          virus Corona dalam 14 hari terakhir?</label
        >
        {{form.kontak_gejala}}
      </div>
      <div>
        <input
          style="margin-top: 20px"
          class="btn btn-primary"
          type="submit"
          value="Submit"
        />
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/assessment/high.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {%block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/high.css' %}" />
{%endblock%} {%block content%}
<div class="high">
  <div class="golonganDiv">
    <h1>Kemungkinan anda terpapar virus Covid-19 tergolong</h1>
    <h1 id="type">TINGGI</h1>
  </div>
  <div class="content">
    <div class="img">
      <img
        src="https://images.vexels.com/media/users/3/193280/isolated/preview/8239ac53cb85b93a6786e3c5e665acfa-covid-19-symptom-girl-headache-by-vexels.png"
        alt="high-img"
      />
    </div>
    <div class="contentText">
      <p>Ini hal yang dapat dilakukan dan rekomendasi agar anda tetap aman</p>
      <ul>
        <li>
          Segera lakukan PCR/swab test di rumah sakit/fasilitas kesehatan
          terdekat
        </li>
        <li>
          Anda diharapkan untuk segera mengisolasi diri anda selama 14 hari
          dirumah, dan hindari kontak fisik dengan orang lain
        </li>
        <li>
          Anda diharapkan tidak keluar rumah untuk melindungi orang-orang
          disekitar anda
        </li>
        <li>
          Patuhi 3M : Memakai masker, Mencuci tangan minimal 20 detik, Menjaga
          jarak dengan orang lain
        </li>
        <li>
          Jika gejala yang anda alami hanya memburuk, segera hubungi rumah
          sakit/fasilitas kesehatan terdekat
        </li>
      </ul>
    </div>
  </div>
  <div>
    <form method="POST" action="{% url 'assessment:retake' %}">
      {% csrf_token %}
      <button class="btn btn-primary">Re-take Assesment</button>
    </form>
  </div>
</div>
{%endblock%}

templates/assessment/low.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {%block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/low.css' %}" />
{%endblock%} {%block content%}
<div class="low">
  <div class="golonganDiv">
    <h1>Kemungkinan anda terpapar virus Covid-19 tergolong</h1>
    <h1 id="type">RENDAH</h1>
  </div>
  <div class="content">
    <div class="img">
      <img
        src="https://images.vexels.com/media/users/3/193239/isolated/preview/e83db85552ee35f6276411c9f19d982d-covid-19-boy-character-icon-by-vexels.png"
        alt="low-img"
      />
    </div>
    <div class="contentText">
      <p>Ini hal yang dapat dilakukan dan rekomendasi agar anda tetap aman</p>
      <ul>
        <li>Coba untuk tetap di rumah dan mengurangi kegiatan di luar</li>
        <li>Patuhi protokol kesehatan</li>
        <li>
          Patuhi 3M : Memakai masker, Mencuci tangan minimal 20 detik, Menjaga
          jarak dengan orang lain
        </li>
        <li>
          Jika anda diharuskan ke luar, prioritaskan ruangan dengan sirkulasi
          udara yang baik
        </li>
      </ul>
    </div>
  </div>
  <div>
    <form method="POST" action="{% url 'assessment:retake' %}">
      {% csrf_token %}
      <button class="btn btn-primary">Re-take Assesment</button>
    </form>
  </div>
</div>
{%endblock%}

templates/assessment/medium.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {%block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/medium.css' %}" />
{%endblock%} {%block content%}
<div class="high">
  <div class="golonganDiv">
    <h1>Kemungkinan anda terpapar virus Covid-19 tergolong</h1>
    <h1 id="type">SEDANG</h1>
  </div>
  <div class="content">
    <div class="img">
      <img
        src="https://images.vexels.com/media/users/3/193236/isolated/preview/1590950fb0eb48ffee67d8d3d86b35ea-covid-19---cone-de-personagem-de-menina-loira-by-vexels.png"
        alt="high-img"
      />
    </div>
    <div class="contentText">
      <p>Ini hal yang dapat dilakukan dan rekomendasi agar anda tetap aman</p>
      <ul>
        <li>
          Anda diharapkan untuk segera mengisolasi diri anda selama 14 hari
          dirumah, dan hindari kontak fisik dengan orang lain
        </li>
        <li>Prioritas aktivitas pada ruangan yang bersirkulasi baik</li>
        <li>
          Jika anda diwajibkan keluar rumah, tolong perhatikan protokol
          kesehatan yang berlaku
        </li>
        <li>
          Patuhi 3M : Memakai masker, Mencuci tangan minimal 20 detik, Menjaga
          jarak dengan orang lain
        </li>
        <li>
          Jika gejala yang anda alami hanya memburuk, segera hubungi rumah
          sakit/fasilitas kesehatan terdekat
        </li>
      </ul>
    </div>
  </div>
  <div>
    <form method="POST" action="{% url 'assessment:retake' %}">
      {% csrf_token %}
      <button class="btn btn-primary">Re-take Assesment</button>
    </form>
  </div>
</div>
{%endblock%}