akun/urls.py
from django.urls import path
from . import views

app_name ='akun'

urlpatterns = [
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.profile_dua , name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.update_profile , name = 'update_profile')
]

coronahworry/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workout/', include(('workout.urls', 'workout'), namespace = 'workout')),
    path('profile/', include(('akun.urls', 'akun'), namespace = 'akun')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('curhat/', include(('komentar.urls', 'komentar'), namespace = 'komentar')),
    path('curhat/', include(('postingan.urls', 'postingan'), namespace = 'postingan')),
    path('', include(('main.urls', 'main'), namespace='main')),
]



workout/urls.py
from django.urls import path
from .views import create_work, list_work, detail_work, all_work
from django.conf.urls import url

app_name = 'workout'

urlpatterns = [
    path('', create_work, name="create"),
    path('all/', all_work, name="all"),
    url(r'^list/$', list_work, name="list"),
    url(r'^detail/(?P<detail_id>[0-9]+)$', detail_work, name="detail"),
]

workout/models.py
from django.db import models

# Create your models here.

class Workout(models.Model):
    TIME = (
        ('0-30 menit', '1'),
        ('30 menit - 1 jam','2'),
        ('1 - 1.5 jam', '3'),
        ('1.5 - 2 jam', '4'),
    )
    surname         = models.CharField(max_length=20)
    work_activity   = models.CharField(max_length=50)
    duration        = models.CharField(max_length=20, choices=TIME, default='0-30 menit')
    description     = models.TextField()
    weight          = models.FloatField()
    height          = models.FloatField()
    bmi             = models.FloatField(null=True)
    state_bmi       = models.CharField(max_length=20, editable=False)
    published       = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}. {}, work={}".format(self.id, self.surname, self.work_activity)

workout/forms.py
from django import forms

class WorkoutForm(forms.Form):
    
    surname         = forms.CharField(max_length=20)
    work_activity   = forms.CharField(max_length=50)
    duration        = forms.CharField(max_length=20)
    description     = forms.CharField(max_length=200, widget=forms.Textarea)
    weight          = forms.FloatField()
    height          = forms.FloatField()
    

workout/views.py
from django.shortcuts import render, redirect
from .models import Workout
from .forms import WorkoutForm
from django.core.paginator import Paginator
import math

# Create your views here.
def create_work(request):
    work_form = WorkoutForm()

    context = {}
    if request.method == "POST":
        surname         = request.POST.get("surname")
        work_activity   = request.POST.get("work_activity")
        duration        = request.POST.get("duration")
        description     = request.POST.get("description")
        weight          = request.POST.get("weight")
        height          = request.POST.get("height")

        if weight :
            weight = float(request.POST.get("weight"))
            height = float(request.POST.get("height"))

        bmi = (weight/(height**2))

        print(bmi)

        state_bmi = ""
        save  = "on"

        #Kondisi untuk state BMI (range)
        if save == "on":
            if (bmi<18.5):
                state_bmi="Underweight"
            elif (bmi>=18.5 and bmi<=24.9):
                state_bmi="Normal"
            elif (bmi>=25 and bmi<=29.9):
                state_bmi="Preobese"
            elif (bmi>=30 and bmi<=34.9):
                state_bmi="Obese Class I"
            elif (bmi>=35 and bmi<=39.9):
                state_bmi="Obese Class II"
            elif (bmi>=40):
                state_bmi="Obese Class III"

            Workout.objects.create(
                surname=surname, 
                work_activity=work_activity, 
                duration=duration,
                description=description, 
                weight=weight,
                height=height,
                bmi=round(bmi, 2),
                state_bmi=state_bmi
                )
            
            return redirect('workout:list')

        context['bmi']          = bmi
        context['state_bmi']    = state_bmi,
        context['work_form']    = work_form

    return render(request, 'workout/index.html', context)

def list_work(request):
    all_work    = Workout.objects.all()
    latest      = all_work[len(all_work)-1] #Mengambil objek yang baru ditambahkan
    a_latest    = latest.state_bmi
    related     = Workout.objects.filter(state_bmi=a_latest).order_by('-published')
    n_related   = len(related)

    works_per_page = 6
    paginator   = Paginator(related, works_per_page)
    page_number = request.GET.get('page')
    page_obj    = paginator.get_page(page_number)
    

    context = {
        'all_work'      : all_work,
        'a_latest'      : a_latest,
        'related'       : related,
        'page_obj'      : page_obj,
        'works_per_page': works_per_page,
        'n_related'     : n_related,
    }

    print(related)
    print(len(page_obj))

    return render(request, 'workout/list.html', context)

def all_work(request):
    all_work    = Workout.objects.all().order_by('-published')
    n_all_work  = len(all_work)

    works_per_page = 6
    paginator   = Paginator(all_work, works_per_page)
    page_number = request.GET.get('page')
    page_obj    = paginator.get_page(page_number)

    context = {
        'all_work'      : all_work,
        'page_obj'      : page_obj,
        'works_per_page': works_per_page,
        'n_all_work'    : n_all_work,
    }
    print(n_all_work)

    return render(request, 'workout/all.html', context)

def detail_work(request, detail_id):
    work_detail = Workout.objects.get(id=detail_id)

    print(work_detail.bmi)
    context = {
        'work_detail' : work_detail,

    }
    return render(request, 'workout/detail.html', context)

templates/workout/all.html
{% extends '../base/base.html' %}
{% load static %}

{% block title %}
    Share Activity & Workout
{% endblock %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'css/workout.css' %}">
{% endblock %}

{% block content %}
<div class="container my-4 py-4">
    <h2 class="text-center mb-4">Calculate your BMI & Share Your Activities</h2>
    <div class="tengah" style="display:flex; justify-content: center;"><a class="btn btn-outline-primary" href="{% url 'workout:create' %}" title="">Yes, Sure</a></div>
</div>


    <h1 class="text-center">All of Activities</h1>
   
    
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for i in page_obj %}
        <div class="card mt-5 px-4" style="background-color: #d9d9e0; padding:10px;  box-shadow: 2px 2px 2px rgba(0,0,0,0.8);">
            <div class="card-header" style="box-shadow: 2px 2px rgba(77, 70, 77, 0.507);">
                <h4 class="text-center">{{i.work_activity}}</h4>
                {% if i.state_bmi == 'Underweight' %}
                    <img src="{% static 'img/workout/white.png' %}" style="position:static; width:50px; height:50px; border-radius:50%; display: block; margin:auto;">
                {% elif i.state_bmi == 'Normal' %}
                    <img src="{% static 'img/workout/ing.webp' %}" style="position:static; width:50px; height:50px; border-radius:50%; display: block; margin:auto;">
                {% elif i.state_bmi == 'Preobese' %}
                    <img src="{% static 'img/workout/pink.png' %}" style="position:static; width:50px; height:50px; border-radius:50%; display: block; margin:auto;">
                {% else %}
                    <img src="{% static 'img/workout/br.webp' %}" style="position:static; width:50px; height:50px; border-radius:50%; display: block; margin:auto;">
                {% endif %}
            </div>
            

            <div class="card-body" style="display:grid; grid-template-columns: auto 1fr; background-color: #d9d9e0; font-family:'Lucida'; row-gap: .3rem; column-gap: .8rem;">
                <div class="kiri">Duration</div>
                <div class="kanan">{{i.duration}}</div>
                <div class="kiri">Surname</div>
                <div class="kanan">{{i.surname}}</div>
                <div class="kiri">BMI</div>
                <div class="kanan">{{i.bmi}}</div>
                <div class="kiri">Range BMI</div>
                <div class="kanan">{{i.state_bmi}}</div>
                <div class="kiri">Published on</div>
                <div class="kanan">{{i.published}}</div>
                <div><a class="btn btn-outline-primary" href="{% url 'workout:detail' i.id %}">Detail</a></div>
            </div>
        </div>
        {% endfor %}
        </div>
        

        {% if n_all_work > works_per_page %}
        <div class="container" style="display:flex; justify-content: center;">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                    {% endif %}
        
                    {% for page in page_obj.paginator.page_range %}
                        {% if page is page_obj.number %}
                        <li class="page-item" aria-current="page">
                            <span class="page-link" href="#">{{page}}
                                <span class="sr-only">(current)</span>
                            </span>
                        </li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                        {% endif %}
                        {% endfor %}
        
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                    {% endif %}
                </ul>
              </nav>
        </div>
        {% endif %}
{% endblock %}

templates/workout/detail.html
{% extends '../base/base.html' %}
{% load static %}

{% block title %}
Detail
{% endblock %}

{% block content %}
<div class="container my-4 py-4">
    <h1 class="text-center mb-3"><b>{{work_detail.work_activity}}</b></h1>

    {% if work_detail.bmi < 20 %}
        <img src="{% static 'img/workout/u.jpg' %}" style="display: block; margin:auto;" width=35% height=40%>

    {% elif work_detail.bmi > 30.0 %}
        <img src="{% static 'img/workout/fe.jpg' %}" style="display: block; margin:auto;" width=60% height=60%>
    
    {% elif 20 <= work_detail.bmi <= 30  %}
        <img src="{% static 'img/workout/basket.png' %}" style="display: block; margin:auto;" width=35% height=50%>

    {% endif %}

    <div class="container mt-5 px-4">
        <h5 class="text-center">Kegiatan ini dilakukan selama {{work_detail.duration}} oleh {{work_detail.surname}}</h5>
        <h5 class="text-center">{{work_detail.surname}} memiliki BMI sebesar {{work_detail.bmi}} dengan kategori {{work_detail.state_bmi}}</h5>
        <div class="card text-justify mt-5 py-4 px-5" style="display: block; margin:auto; background-color:#d9d9e0; justify-content:center; text-align:center; padding:30px; box-shadow: 2px 2px 2px rgba(0,0,0,0.8);">
            <h5 class="text-center"><b>Activity Description</b></h5>
            <p style="text-align:justify;">{{work_detail.description}}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/workout/index.html
{% extends '../base/base.html' %}
{% load static %}

{% block title %}
    Create Workout
{% endblock %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'css/workout.css' %}">
{% endblock %}


{% block content %}
    <div class="container my-3">
        <div class="container mt-5">
            <h2 class="text-center">Add and Share Your Activity</h2>
        </div>
    <div class="container" style="margin-top:50px; min-height: 300px; display:flex; justify-content: center;">
            <div class="col-md-10 col-sm-12 col-xs-12">
                <div class="tab-bmi" style="background-color: #d9d9e0;">
                        <form method="post">
                            {% csrf_token %}
                            <div class="col-12 my-4 pt-4">
                                <label for="surname">Your Surname : </label>
                                <input type="text" name="surname" class="form-control" required>
                            </div>

                            <div class="col-12 my-4">
                                <label for="work_activity">Title of Your Activity : </label>
                                <input type="text" name="work_activity" class="form-control" required>
                            </div>

                            <div class="col-12 my-4">
                                <label>Duration :</label>
                                <select name="duration" class="form-control" required>
                                    <option value="0-30 menit">0-30 menit</option>
                                    <option value="30 menit - 1 jam">30 menit - 1 jam</option>
                                    <option value="1 - 1.5 jam">1 - 1.5 jam</option>
                                    <option value="1.5 - 2 jam">1.5 - 2 jam</option>
                                </select>
                            </div>
                    

                            <div class="col-12 my-4">
                                <label for="description">Description: </label>
                                <textarea name="description" class="form-control" required></textarea>
                            </div>

                            <div class="col-12 my-4">
                                <label for="weight">Weight (kg): </label>
                                <input type="number" step="any" name="weight" class="form-control" required>
                            </div>

                            <div class="col-12 my-4">
                                <label for="height">Height (m): </label>
                                <input type="number" step="any" name="height" class="form-control" required>
                            </div>

                            
                              <button type="submit" class="btn btn-primary my-4 ml-4 px-4 " action="{% url 'workout:create' %}">Submit</button>
                        </form>
                    </div>
        </div>
    </div>
    </div>
        
{% endblock %}